### ISSUE TITLE
Unable to configure cmake build with compat being a separate object library

### ISSUE THREAD

**Issue by apropp-molex** [CESNET/libyang#1058]
Hi,

On the most recent [commit](https://github.com/CESNET/libyang/commit/e21c8bf31241449663880d23cc5519b9b588d522) cmake fails to configure a build. `cmake` version is 3.10.2. Command used was default `cmake ..`. Error message is reproduced below:

```sh
CMake Error at src/user_types/CMakeLists.txt:4 (target_link_libraries):
  Target "compat" of type OBJECT_LIBRARY may not be linked into another
  target.  One may link only to STATIC or SHARED libraries, or to executables
  with the ENABLE_EXPORTS property set.
Call Stack (most recent call first):
  src/user_types/CMakeLists.txt:9 (USER_TYPE_PLUGIN)


CMake Error at src/user_types/CMakeLists.txt:4 (target_link_libraries):
  Target "compat" of type OBJECT_LIBRARY may not be linked into another
  target.  One may link only to STATIC or SHARED libraries, or to executables
  with the ENABLE_EXPORTS property set.
Call Stack (most recent call first):
  src/user_types/CMakeLists.txt:9 (USER_TYPE_PLUGIN)


CMake Error at CMakeLists.txt:339 (target_link_libraries):
  Target "compat" of type OBJECT_LIBRARY may not be linked into another
  target.  One may link only to STATIC or SHARED libraries, or to executables
  with the ENABLE_EXPORTS property set.


CMake Error at CMakeLists.txt:345 (target_link_libraries):
  Target "compat" of type OBJECT_LIBRARY may not be linked into another
  target.  One may link only to STATIC or SHARED libraries, or to executables
  with the ENABLE_EXPORTS property set.
```

**Comment by igortern** [comment]
Note that according to cmake documentation [https://cmake.org/cmake/help/v3.9/command/add_library.html#object-libraries](url), when object library is referred to as a dependency in add_executable(), add_library(), target_link_library(), it should be done using $<TARGET_OBJECTS:objlib> rather than just objlib.
Replacing "compat" to $<TARGET_OBJECTS:compat> in all dependencies in CMakeLists.txt and src/user_types/CMakeLists.txt fixed the issue.

**Comment by apropp-molex** [comment]
Thanks for the information. Although I do think it should be fixed within the library as well. As other people will also run into this issue.

**Comment by igortern** [comment]
Yes, absolutely

**Comment by michalvasko** [comment]
Right, thanks for the hint. Should be fixed now.

Regards,
Michal

**Comment by igortern** [comment]
Not quite fixed yet. Need to fix also src/user_types/CMakeLists.txt

**Comment by michalvasko** [comment]
Ah, right... Should be okay now, I hope.

Regards,
Michal

**Comment by igortern** [comment]
Thanks.
Regards,
Igor

**Comment by apropp-molex** [comment]
Hi Igor and Michal,

Thanks for pointing out the fix and implementing it. Much appreciated. Closing this issue off as everything appears to be fine now.
