### ISSUE TITLE
Unable to print data tree in the XML format

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1099]
In FRR I found a curious problem where I can print a data tree in the JSON format but not in the XML format. This only happens for state data that is created using the `lyd_new_path()` API.

I wrote this simple program to demonstrate the problem: https://pastebin.com/raw/ujTqKXJU

When the data is loaded from an external file (like [1]), everything works fine, the data can be printed in both the JSON and XML formats. When the data is created manually using the `lyd_new_path()` API, it can be printed in the JSON format only. In one case, where `lyd_validate()` is called with the `LYD_OPT_GET` flag, the data can't be printed in any format at all (and no errors are logged).

I'm using the latest libyang from `devel` and the problem happens even with `-DENABLE_CACHE=OFF`. I don't know if this is a bug or an API misuse. Any help would be appreciated!

NOTE: the frr-vrf and frr-zebra YANG modules can be found here: https://github.com/FRRouting/frr/tree/master/yang

[1] https://pastebin.com/raw/syRPJXFQ

**Comment by michalvasko** [comment]
Hi,
I have fixed the example app, it worked fine then. The core of the problem here is that validating with `LYD_OPT_GET` does not modify (add) default values so an empty data tree is being appended to.

Regards,
Michal

[test.c](https://github.com/CESNET/libyang/files/4707481/test.c.txt)

**Comment by rwestphal** [comment]
@michalvasko Thanks for your help. Indeed, that explains why the `LYD_OPT_GET` case wasn't working. However, I still have the same problem where I can print the data tree in the JSON format but not in the XML format when I use `lyd_validate()` with the `LYD_OPT_DATA | LYD_OPT_DATA_NO_YANGLIB` options. I've created a separate test program for that particular case only: https://pastebin.com/raw/stdrAQW1

Could you help me to identify what's going wrong in that case? This is the actual problem we're having in FRR.

**Comment by michalvasko** [comment]
Hi Renato,
okay, there were some minor problems that should be fixed now. But be aware that in your use-case there are several top-level default containers preceding the explicit data so unless you use `LYP_WITHSIBLINGS`, nothing will be printed (JSON printer actually had the bug).

Regards,
Michal

**Comment by rwestphal** [comment]
Awesome :) Thanks for the clarification and for the fix in the JSON printer. It indeed makes sense that `LYP_WITHSIBLINGS` needs to be used in that case. I'll close this issue now.
