### ISSUE TITLE
Double free during notification parsing

### ISSUE THREAD

**Issue by vijaykalkoti** [CESNET/libyang#1186]
Stack trace below for reference.
```
0x00007f67aa467337 in raise () from /lib64/libc.so.6
0x00007f67aa468a28 in abort () from /lib64/libc.so.6
0x00007f67aa4a9e87 in __libc_message () from /lib64/libc.so.6
0x00007f67aa4b2679 in _int_free () from /lib64/libc.so.6
0x00007f67ab551c13 in lyd_free_value (value=..., value_type=LY_TYPE_BITS, value_flags=0 '\000', type=0x7f679c0716c8, value_str=0x7f679c0b2cc0 "", old_val=0x0, old_val_type=0x0,
    old_val_flags=0x0) at workspace/libyang-workspace/src/tree_data.c:6188
0x00007f67ab4d58c9 in lyp_parse_value (type=0x7f679c0716c8, value_=0x7f679c1bd518, xml=0x0, leaf=0x7f679c1bd4e0, attr=0x0, local_mod=0x7f679c05a3c0, store=1, dflt=0, trusted=0)
    at workspace/libyang-workspace/src/parser.c:1982
0x00007f67ab4c7cce in resolve_unres_data_item (node=0x7f679c1bd4e0, type=UNRES_LEAFREF, ignore_fail=2, failed_when=0x0)
    at workspace/libyang-workspace/src/resolve.c:8220
0x00007f67ab4c8b06 in resolve_unres_data (ctx=0x7f679c020ec0, unres=0x7f679c1ba820, root=0x7f67a66ba8e0, options=34368)
    at workspace/libyang-workspace/src/resolve.c:8595
0x00007f67ab555a04 in lyd_defaults_add_unres (root=0x7f67a66ba8e0, options=34368, ctx=0x7f679c020ec0, modules=0x0, mod_count=0, data_tree=0x0, act_notif=0x7f679c1bdc30,
    unres=0x7f679c1ba820, wd=1) at workspace/libyang-workspace/src/tree_data.c:7862
0x00007f67ab501dd0 in lyd_parse_xml (ctx=0x7f679c020ec0, root=0x7f679c1bb718, options=34368) at workspace/libyang-workspace/src/parser_xml.c:744
```

**Comment by vijaykalkoti** [comment]
```
- Observing double free issue while parsing below XML.
- 
- 
- ******
- <notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
- 	<eventTime>2020-08-31T11:10:02Z</eventTime>
- 	<hardware-state-oper-enabled xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
- 		<name>RRH</name>
- 		<admin-state>unlocked</admin-state>
- 		<alarm-state/>
- 	</hardware-state-oper-enabled>
- </notification>
- *****
- 
```

**Comment by michalvasko** [comment]
Hi,
what *libyang* version are you using?

**Comment by vijaykalkoti** [comment]
We did try with latest master. Observing same issue.

**Comment by michalvasko** [comment]
Hi,
okay, can you please provide `valgrind` output, for example? I would prefer to fix it based on the information you provide because I think if I tried to reproduce it, I would not succeed, it seems there is a leafref used.

**Comment by vijaykalkoti** [comment]
Used master latest code to generate this. Also, please refer to the code snippet for your reference.

==22887== Memcheck, a memory error detector
==22887== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22887== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==22887== Command: ./a.out
==22887==
==22887== Invalid free() / delete / delete[] / realloc()
==22887==    at 0x4C2AF9D: free (vg_replace_malloc.c:540)
==22887==    by 0x4EB4C54: lyd_free_value (tree_data.c:6096)
==22887==    by 0x4E63714: lyp_parse_value (parser.c:2000)
==22887==    by 0x4E59091: resolve_unres_data_item (resolve.c:8202)
==22887==    by 0x4E59894: resolve_unres_data (resolve.c:8576)
==22887==    by 0x4EBFEE3: lyd_defaults_add_unres (tree_data.c:8116)
==22887==    by 0x4E845E9: lyd_parse_xml (parser_xml.c:750)
==22887==    by 0x400A6F: main (issue.c:40)
==22887==  Address 0x5fd0e50 is 0 bytes inside a block of size 56 free'd
==22887==    at 0x4C2AF9D: free (vg_replace_malloc.c:540)
==22887==    by 0x4EB4C54: lyd_free_value (tree_data.c:6096)
==22887==    by 0x4E63714: lyp_parse_value (parser.c:2000)
==22887==    by 0x4E629BD: lyp_parse_value (parser.c:1718)
==22887==    by 0x4E59091: resolve_unres_data_item (resolve.c:8202)
==22887==    by 0x4E59894: resolve_unres_data (resolve.c:8576)
==22887==    by 0x4EBFEE3: lyd_defaults_add_unres (tree_data.c:8116)
==22887==    by 0x4E845E9: lyd_parse_xml (parser_xml.c:750)
==22887==    by 0x400A6F: main (issue.c:40)
==22887==  Block was alloc'd at
==22887==    at 0x4C2BFB9: calloc (vg_replace_malloc.c:762)
==22887==    by 0x4E619AC: lyp_parse_value (parser.c:1346)
==22887==    by 0x4E629BD: lyp_parse_value (parser.c:1718)
==22887==    by 0x4E82B65: xml_get_value (parser_xml.c:95)
==22887==    by 0x4E839B0: xml_parse_data (parser_xml.c:461)
==22887==    by 0x4E83C1F: xml_parse_data (parser_xml.c:515)
==22887==    by 0x4E843C0: lyd_parse_xml (parser_xml.c:688)
==22887==    by 0x400A6F: main (issue.c:40)
==22887==
Removing event-time==22887==


int main()
{
    struct lyxml_elem *xml, *ev_time;

    struct ly_ctx * _ly_ctx = ly_ctx_new(NULL, 0);

    ly_ctx_set_searchdir( _ly_ctx, PATH1);

    lys_parse_path( _ly_ctx, PATH1"/Imported_Models/ietf-hardware.yang", LYS_IN_YANG);

    struct lys_module *schema_ctx = ly_ctx_get_module( _ly_ctx, "ietf-hardware", NULL, 1 );
    lys_features_enable(schema_ctx, "hardware-state");

    const char buffer[] = "<notification xmlns=\"urn:ietf:params:xml:ns:netconf:notification:1.0\"> <eventTime>2020-08-31T11:10:02Z</eventTime> <hardware-state-oper-enabled xmlns=\"urn:ietf:params:xml:ns:yang:ietf-hardware\"> <name>MTIRRH</name> <admin-state>unlocked</admin-state> <alarm-state/> </hardware-state-oper-enabled> </notification>";

    xml = lyxml_parse_mem( _ly_ctx, buffer, LYXML_PARSE_NOMIXEDCONTENT);

    if( NULL == xml )
    {
        printf("Failed to parse XML\n");
    }

    printf("Removing event-time");
    /* eventTime */
    LY_TREE_FOR(xml->child, ev_time) {
        if (!strcmp(ev_time->name, "eventTime")) {
             //(*notif)->datetime = lydict_insert( _ly_ctx, ev_time->content, 0);
             /* lyd_parse does not know this element */
             lyxml_free(_ly_ctx, ev_time);
             break;
        }
    }

    struct lyd_node *data = lyd_parse_xml( _ly_ctx, &xml->child, (LYD_OPT_NOTIF | LYD_OPT_DESTRUCT | LYD_OPT_NOEXTDEPS | LYD_OPT_STRICT), NULL);

    return 0;
}

**Comment by vijaykalkoti** [comment]
Below patch resolves this. But, I don't think it's the right fix.
Request expert opinion on this.

diff --git a/src/parser.c b/src/parser.c
index 9c744f1..f3dfc7b 100755
--- a/src/parser.c
+++ b/src/parser.c
@@ -1226,6 +1226,7 @@ lyp_parse_value(struct lys_type *type, const char **value_, struct lyxml_elem *x
     uint8_t *val_flags, old_val_flags;
     struct lyd_node *contextnode;
     struct ly_ctx *ctx = type->parent->module->ctx;
+    uint8_t  bits_leafref = 0;

     assert(leaf || attr);

@@ -1721,6 +1722,10 @@ lyp_parse_value(struct lys_type *type, const char **value_, struct lyxml_elem *x
         }

         type = t;
+        if( LY_TYPE_BITS == type->base )
+        {
+            bits_leafref = 1;
+        }
         break;

     case LY_TYPE_STRING:
@@ -1978,7 +1983,7 @@ lyp_parse_value(struct lys_type *type, const char **value_, struct lyxml_elem *x
     }

     /* free backup */
-    if (store) {
+    if (store && (!bits_leafref)) {
         lyd_free_value(old_val, old_val_type, old_val_flags, type, old_val_str, NULL, NULL, NULL);
         lydict_remove(ctx, old_val_str);
     }

**Comment by michalvasko** [comment]
Hi,
okay, should work now, thanks for the example. Your patch was almost correct.

**Comment by vijaykalkoti** [comment]
Thank You!
I was going through the commit that is shared above. I did try this, but the issue was still occurring.
What I observed is, when the LEAFREF is resolved to BITS, the type-base of leaf is updated to BITS, and leads to double free again.

Please correct us, if our understanding is wrong here.

**Comment by michalvasko** [comment]
I have just tested it with your example including the referenced data so they are resolved and stored, there was no leak. Please, provide an example that reproduces the leak, otherwise I cannot help you.
