### ISSUE TITLE
Yang parsing error around list keys

### ISSUE THREAD

**Issue by esend7881** [CESNET/libyang#1192]
### Problem:
I am working to install an opendaylight yang file (see reference files below) and I am getting this error:

```
$ sysrepoctl -i opendaylight-flow-types@2013-10-26.yang -a
[ERR]: Missing keyword "key" as a child to "list". (path: /openflow-instruction:instruction-container/instruction-choice/write-actions-case/write-actions/action)
[ERR]: Module "openflow-instruction" parsing failed.
[ERR]: Importing "openflow-instruction" module into "openflow-protocol" failed.
[ERR]: Module "openflow-protocol" parsing failed.
[ERR]: Importing "openflow-protocol" module into "opendaylight-meter-types" failed.
[ERR]: Module "opendaylight-meter-types" parsing failed.
[ERR]: Importing "opendaylight-meter-types" module into "opendaylight-flow-types" failed.
[ERR]: Module "opendaylight-flow-types" parsing failed.
sysrepoctl error: Failed to install module "opendaylight-flow-types@2013-10-26.yang" (libyang error)
```

I know this yang file installs just fine in the Opendaylight project. The main reason I am trying to install it in sysrepo is because we need an axuillary config datastore.

### My questions:
1. Is there a way to run/install libyang (or sysrepo) so that it is not as strict in parsing, or I can selectively reduce errors to warnings?
2. Did Opendaylight fork out their YANG syntax, which explains why they don't need the "key" field, etc?
3. Ultimately, how do I successfully install Opendaylight yang files into sysrepo without modifying ODL's yang files?

### My Environment:
- libyang 1.0.184  `cmake -DGEN_LANGUAGE_BINDINGS=ON`
- sysrepo 1.4.70 `cmake -DGEN_LANGUAGE_BINDINGS=ON`
- Opendaylight Sodium

### Reference Files:
- [opendaylight-flow-types.yang](https://github.com/opendaylight/openflowplugin/blob/stable/sodium/model/model-flow-base/src/main/yang/opendaylight-flow-types.yang) 
- [more yangs here](https://github.com/opendaylight/openflowplugin/tree/stable/sodium/model/model-flow-base/src/main/yang) 
- The rest of the yang files are scattered about. 
- That said, I zipped them up and attached them here: [yang.zip](https://github.com/CESNET/libyang/files/5177135/yang.zip)

### Also
Since I can't really tell if the problem is on ODL's side as well, I made a couple tickets over at their Jira board:
https://jira.opendaylight.org/browse/OPNFLWPLUG-1103
https://jira.opendaylight.org/browse/OPNFLWPLUG-1104

**Comment by michalvasko** [comment]
Hi,
I did not manage to reproduce it using the current `devel` *libyang* and *sysrepo* so perhaps the problem was fixed.

**Comment by esend7881** [comment]
I actually found pyang would report similar problems in the ODL yang files.

Is it possible ODL and the devel libyang has updated the yang syntax
definitions, especially surrounding keys and lists?

When I get back to my office I will try the devel versions.

**Comment by esend7881** [comment]
> Hi,
> I did not manage to reproduce it using the current `devel` _libyang_ and _sysrepo_ so perhaps the problem was fixed.

@michalvasko 
I just tried the current `devel` branch of both libyang and sysrepo and re-ran the install:

```
# sysrepoctl -i opendaylight-flow-types@2013-10-26.yang -s . -v 4
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[WRN]: Missing status in deprecated subtree (/opendaylight-inventory:node-updated/node-ref), inheriting.
[WRN]: Missing status in deprecated subtree (/opendaylight-inventory:node-updated/node), inheriting.
[WRN]: Missing status in deprecated subtree (/opendaylight-inventory:node-connector-updated/node-connector-ref), inheriting.
[WRN]: Missing status in deprecated subtree (/opendaylight-inventory:node-connector-updated/node-connector), inheriting.
[WRN]: Missing status in deprecated subtree (/opendaylight-inventory:node-removed/node-ref), inheriting.
[WRN]: Missing status in deprecated subtree (/opendaylight-inventory:node-connector-removed/node-connector-ref), inheriting.
[ERR]: Missing keyword "key" as a child to "list". (path: /openflow-instruction:instruction-container/instruction-choice/write-actions-case/write-actions/action)
[ERR]: Module "openflow-instruction" parsing failed.
[ERR]: Importing "openflow-instruction" module into "openflow-protocol" failed.
[ERR]: Module "openflow-protocol" parsing failed.
[ERR]: Importing "openflow-protocol" module into "opendaylight-meter-types" failed.
[ERR]: Module "opendaylight-meter-types" parsing failed.
[ERR]: Importing "opendaylight-meter-types" module into "opendaylight-flow-types" failed.
[ERR]: Module "opendaylight-flow-types" parsing failed.
sysrepoctl error: Failed to install module "opendaylight-flow-types@2013-10-26.yang" (libyang error)

```
So I am still seeing the parsing errors. Notably **[ERR]: Missing keyword "key" as a child to "list". (path: /openflow-instruction:instruction-container/instruction-choice/write-actions-case/write-actions/action)**

Did you do something different when installing the yang model to avoid this error?

**Comment by michalvasko** [comment]
I am on the same commits, my output
```
> ./sysrepoctl -a -v4 -s ../../../Downloads/yang -i ../../../Downloads/yang/opendaylight-flow-types@2013-10-26.yang 
[INF]: Libyang internal module "yang" was installed.
[INF]: File "ietf-datastores@2018-02-14.yang" was installed.
[INF]: Sysrepo internal dependency module "ietf-datastores" was installed.
[INF]: File "ietf-yang-library@2019-01-04.yang" was installed.
[INF]: Sysrepo internal module "ietf-yang-library" was installed.
[INF]: File "sysrepo-monitoring@2020-04-17.yang" was installed.
[INF]: Sysrepo internal module "sysrepo-monitoring" was installed.
[INF]: File "ietf-netconf@2011-06-01.yang" was installed.
[INF]: Sysrepo internal dependency module "ietf-netconf" was installed.
[INF]: File "ietf-netconf-with-defaults@2011-06-01.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF]: File "ietf-netconf-notifications@2012-02-06.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF]: File "ietf-origin@2018-02-14.yang" was installed.
[INF]: Sysrepo internal module "ietf-origin" was installed.
[INF]: Datastore copied from <startup> to <running>.
[INF]: Module "opendaylight-flow-types" scheduled for installation.
[INF]: File "opendaylight-match-types@2013-10-26.yang" was installed.
[INF]: File "opendaylight-l2-types@2013-08-27.yang" was installed.
[INF]: File "opendaylight-inventory@2013-08-19.yang" was installed.
[INF]: File "yang-ext@2013-07-09.yang" was installed.
[INF]: File "opendaylight-arbitrary-bitmask-fields@2016-01-30.yang" was installed.
[INF]: File "opendaylight-ipv6-arbitrary-bitmask-fields@2016-02-24.yang" was installed.
[INF]: File "opendaylight-action-types@2013-11-12.yang" was installed.
[INF]: File "opendaylight-meter-types@2013-09-18.yang" was installed.
[INF]: File "openflow-protocol@2013-07-31.yang" was installed.
[INF]: File "openflow-types@2013-07-31.yang" was installed.
[INF]: File "openflow-extensible-match@2015-02-25.yang" was installed.
[INF]: File "openflow-instruction@2013-07-31.yang" was installed.
[INF]: File "openflow-action@2015-02-03.yang" was installed.
[INF]: File "opendaylight-multipart-types@2017-01-12.yang" was installed.
[INF]: Applying scheduled changes.
[INF]: File "opendaylight-flow-types@2013-10-26.yang" was installed.
[INF]: Module "opendaylight-flow-types" was installed.
[INF]: Dependency module "opendaylight-multipart-types" was installed.
[INF]: Scheduled changes applied.
```
Are you sure you are actually using the latest *libyang* and it is not hidden by some other version?

**Comment by esend7881** [comment]
I'm using the libyang from aa6dc43957cdb6d535519e2fcacd81ee34896180 and I show my `cmake` options, are you using different cmake options to compile libyang?

Beyond that, here are my yum installs in my CentOS 7 VM:
```
yum -y install dnf
yum -y install epel-release
yum -y update
yum -y install python36 python3-pip net-tools iperf3 psmisc wget
yum -y install java-1.8.0-openjdk-devel git


yum -y install gcc make rpm-build redhat-rpm-config python-devel desktop-file-utils groff graphviz checkpolicy selinux-policy-devel python-sphinx python-twisted-core python-zope-interface python-six libcap-ng-devel autoconf automake libtool openssl-devel gcc-c++ readline-devel readline-static.x86_64

yum -y clean all
pip3 install --upgrade pip

yum -y remove swig
yum -y install libcmocka libcmocka-devel libssh libssh-devel curl-devel devscripts debhelper nodejs python3-virtualenv swig3
```

I wonder if a version of one of the installs changed something?

**Comment by michalvasko** [comment]
Hi,
okay, I managed to reproduce it on my CentOS 7 VM and after that I learned that the modules I was using were a bit different for some reason, sorry about that. So anyway, the error is correct, there is a `config true` list on the path that has no `key` statement, that is forbidden.

**Comment by esend7881** [comment]
Interesting, wouldn't expect ODL to have a syntax error on their offical
yang models. I'll update my ticket on their jira board with this next I'm
at my desk.
