### ISSUE TITLE
ly2: broken for unions (or typedef that use e.g., inet:ip-address)

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1532]
There appear to be (multiple?) issues with type union in the latest code

Reproducing at least one failure

main.yang:

```
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;

  import "ietf-inet-types" {
    prefix inet;
  }

  typedef optional-ip-address {
    type union {
      type inet:ip-address;
      type string {
        pattern "";
      }
    }
  }

  container c {
    list nexthop {
      key gateway;
      leaf gateway {
        type optional-ip-address;
      }
      leaf v {
        type uint8;
      }
    }
  }
}
```

main.c:

```
#include <assert.h>
#include <err.h>
#include <stddef.h>
#include <stdio.h>

#include <libyang/libyang.h>

int main(int argc, char **argv)
{
    struct ly_ctx *ctx = NULL;
    struct lyd_node *cnode, *mnode, *node = NULL;
    const struct lys_module *main = NULL;

    assert(!ly_ctx_new(".", 0, &ctx));
    assert(main = ly_ctx_load_module(ctx, "main", NULL, NULL));
    assert(!lyd_new_inner(NULL, main, "c", 0, &cnode));
    assert(!lyd_new_path(cnode, ctx, "/main:c/nexthop[gateway='10.0.0.1']/v", "2", LYD_NEW_PATH_UPDATE, &node));
    assert(!lyd_new_path(cnode, ctx, "/main:c/nexthop[gateway='2100::1']/v", "3", LYD_NEW_PATH_UPDATE, &node));
    assert(!lyd_find_path(cnode, "/main:c/nexthop[gateway='10.0.0.1']/v", 0, &mnode));
    lyd_print_file(stdout, cnode, LYD_JSON, LYD_PRINT_WITHSIBLINGS);
}
```

output:
```
test: /home/chopps/w/ly2/src/tree_data_helpers.c:494: ly_dup_prefix_data: Assertion `!prefix_data' failed.
Aborted (core dumped)
```

**Comment by michalvasko** [comment]
Should be fixed. I believe this bug was present for quite some time but we did not encounter it before.

**Comment by choppsv1** [comment]
> Should be fixed. I believe this bug was present for quite some time but we did not encounter it before.

I will check it out. If it only fixed a long standing bug it probably won't fix my issue since it just showed up with the new types plugins/hashing

**Comment by choppsv1** [comment]
Still broken, although the simple case above no longer asserts, here's some output from a gdb session:
```
(gdb) sib_walk config1->dnode
Args Passed: config1->dnode
/lib(1)/
/lib(1)/
/routing(1)/
/routing/control-plane-protocols(1)/
/routing/control-plane-protocols/control-plane-protocol(16)/
/routing/control-plane-protocols/control-plane-protocol/type(4): frr-staticd:staticd
/routing/control-plane-protocols/control-plane-protocol/name(4): staticd
/routing/control-plane-protocols/control-plane-protocol/vrf(4): default
/routing/control-plane-protocols/control-plane-protocol/staticd(1)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list(16)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/prefix(4): 10.40.0.0/13
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/afi-safi(4): frr-routing:ipv4-unicast
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list(16)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/table-id(4): 0
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/distance(4): 1
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/tag(4): 0
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops(1)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop(16)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/nh-type(4): ip4-ifindex
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/vrf(4): default
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/gateway(4): 100.0.0.1
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/interface(4): bad_input
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/bh-type(4): null
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/onlink(4): false
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/mpls-label-stack(1)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list(16)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/prefix(4): 2001::/53
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/afi-safi(4): frr-routing:ipv6-unicast
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list(16)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/table-id(4): 0
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/distance(4): 1
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/tag(4): 0
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops(1)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop(16)/
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/nh-type(4): ip6
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/vrf(4): default
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/gateway(4): 2100::1
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/interface(4): (null)
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/bh-type(4): null
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/onlink(4): false
/routing/control-plane-protocols/control-plane-protocol/staticd/route-list/path-list/frr-nexthops/nexthop/mpls-label-stack(1)/
/lib(1)/
/lib/vrf(16)/
/lib/vrf/name(4): default

(gdb) p path
$5 = 0x5555558dc010 "/frr-routing:routing/control-plane-protocols/control-plane-protocol[type='frr-staticd:staticd'][name='staticd'][vrf='default']/frr-staticd:staticd/route-list[prefix='2001::/53'][afi-safi='frr-routing:ipv6-unicast']/path-list[table-id='0'][distance='1']/frr-nexthops/nexthop[nh-type='ip6'][vrf='default'][gateway='2100::1'][interface='(null)']"
(gdb) call yang_dnode_get(config1->dnode, path)
$6 = (struct lyd_node *) 0x0

(gdb) call lyd_find_xpath(config1->dnode, path, 0, &target)
$10 = LY_EINVAL

(gdb) call lyd_find_xpath(config1->dnode, path, &target)
$11 = LY_SUCCESS
(gdb) p *(struct ly_set *)target
$14 = {size = 0, count = 0, {dnodes = 0x5555558cd640, snodes = 0x5555558cd640, objs = 0x5555558cd640}}
```
The count is zero, it should have found the node, lyd_find_xpath should not have returned LY_EINVAL.

**Comment by choppsv1** [comment]
New repo code (I removed the "v" leaf to more mimic the actual frr code)... The find works for ipv4, but not for ipv6

main.c

```
#include <assert.h>
#include <err.h>
#include <stddef.h>
#include <stdio.h>

#include <libyang/libyang.h>

int main(int argc, char **argv)
{
    struct ly_ctx *ctx = NULL;
    struct lyd_node *cnode, *mnode, *node = NULL;
    const struct lys_module *main = NULL;

    assert(!ly_ctx_new(".", 0, &ctx));
    assert(main = ly_ctx_load_module(ctx, "main", NULL, NULL));
    assert(!lyd_new_inner(NULL, main, "c", 0, &cnode));
    assert(!lyd_new_path(cnode, ctx, "/main:c/nexthop[gateway='10.0.0.1']", "", LYD_NEW_PATH_UPDATE, &node));
    assert(!lyd_new_path(cnode, ctx, "/main:c/nexthop[gateway='2100::1']", "", LYD_NEW_PATH_UPDATE, &node));
    lyd_print_file(stdout, cnode, LYD_JSON, LYD_PRINT_WITHSIBLINGS);
    assert(!lyd_find_path(cnode, "/main:c/nexthop[gateway='10.0.0.1']", 0, &mnode));
    assert(!lyd_find_path(cnode, "/main:c/nexthop[gateway='2100::1']", 0, &mnode));
}
```

main.yang

```
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;

  import "ietf-inet-types" {
    prefix inet;
  }

  typedef optional-ip-address {
    type union {
      type inet:ip-address;
      type string {
        pattern "";
      }
    }
  }

  container c {
    list nexthop {
      min-elements 1;
      key "gateway";
      leaf gateway {
        type optional-ip-address;
      }
    }
  }
}
```

Results:
```
(default) [08:07:07 rlk:~/w/y2bug]$ ./test
{
  "main:c": {
    "nexthop": [
      {
        "gateway": "10.0.0.1"
      },
      {
        "gateway": "2100::1"
      }
    ]
  }
}
test: main.c:21: main: Assertion `!lyd_find_path(cnode, "/main:c/nexthop[gateway='2100::1']", 0, &mnode)' failed.
Aborted (core dumped)
```

**Comment by choppsv1** [comment]
The following fixes the problem; however, I believe I'm just doing this by bypassing the enhancement of a plugin specialized hash function so I don't think this is a good fix.

```
1 file changed, 11 insertions(+), 2 deletions(-)
src/plugins_types/ipv6_address.c | 13 +++++++++++--

modified   src/plugins_types/ipv6_address.c
@@ -63,6 +63,10 @@ lyplg_type_free_ipv6_address(const struct ly_ctx *ctx, struct lyd_value *value)
     }
 }
 
+static const void *
+lyplg_type_print_ipv6_address(const struct ly_ctx *ctx, const struct lyd_value *value, LY_VALUE_FORMAT format,
+                              void *UNUSED(prefix_data), ly_bool *dynamic, size_t *value_len);
+
 /**
  * @brief Validate and store value of the ietf-inet-types ipv6-address type.
  * Implementation of ::lyplg_type_store_clb.
@@ -211,6 +215,9 @@ lyplg_type_store_ipv6_address(const struct ly_ctx *ctx, const struct lysc_type *
             ret = lydict_insert(ctx, value_len ? value : "", value_len, &storage->_canonical);
             LY_CHECK_GOTO(ret, cleanup);
         }
+    } else {
+        /* Cause canonical to be stored */
+        (void)lyplg_type_print_ipv6_address(ctx, storage, LY_VALUE_CANON, NULL, NULL, NULL);
     }
 
 cleanup:
@@ -379,7 +386,8 @@ const struct lyplg_type_record plugins_ip_address[] = {
         .plugin.validate = NULL,
         .plugin.compare = lyplg_type_compare_ipv6_address,
         .plugin.print = lyplg_type_print_ipv6_address,
-        .plugin.hash = lyplg_type_hash_ipv6_address,
+        // .plugin.hash = lyplg_type_hash_ipv6_address,
+        .plugin.hash = lyplg_type_hash_simple,
         .plugin.duplicate = lyplg_type_dup_ipv6_address,
         .plugin.free = lyplg_type_free_ipv6_address
     },
@@ -393,7 +401,8 @@ const struct lyplg_type_record plugins_ip_address[] = {
         .plugin.validate = NULL,
         .plugin.compare = lyplg_type_compare_ipv6_address,
         .plugin.print = lyplg_type_print_ipv6_address,
-        .plugin.hash = lyplg_type_hash_ipv6_address,
+        // .plugin.hash = lyplg_type_hash_ipv6_address,
+        .plugin.hash = lyplg_type_hash_simple,
         .plugin.duplicate = lyplg_type_dup_ipv6_address,
         .plugin.free = lyplg_type_free_ipv6_address
     },
```

**Comment by michalvasko** [comment]
I am working on it right now and probably close to finding the problem.

**Comment by michalvasko** [comment]
What a dumb mistake, but those are the most difficult to find. I have added your test, thanks for that.

**Comment by choppsv1** [comment]
It's passing the tests it used to fail. I'd say OK to merge. :)

**Comment by michalvasko** [comment]
Great, but what do you mean, the commit is in `libyang2` branch already.

**Comment by choppsv1** [comment]
Sorry I thought you had asked me to test it. Didn't notice it was merged. :)
