### ISSUE TITLE
yanglint SIGSEGV on enum

### ISSUE THREAD

**Issue by gvub** [CESNET/libyang#1621]
When using yanglint from libyang2 (devel branch, from today), some deviations modules generate SIGSEGV.
You can refer to the gdb trace below (for 2 different deviation modules).
Yanglint from libyang1 validates those modules successfully. As do Pyang and Yanger.
I can prepare a minimal reproducible example YANG if necessary.

```
Starting program: /home/user1/local/libyang2/bin/yanglint -p . vendor-eth-trunk-deviations.yang
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
libyang err : Memory allocation failed.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ef9734 in lys_compile_iffeature (ctx=0x55555556c2f0, qname=0x55555559efa0, iff=0x7fffffff8820)
    at /home/user1/libyang/src/schema_features.c:283
283         for (i = j = 0; c[i]; i++) {
(gdb) bt
#0  0x00007ffff7ef9734 in lys_compile_iffeature (ctx=0x55555556c2f0, qname=0x55555559efa0, iff=0x7fffffff8820)
    at /home/user1/libyang/src/schema_features.c:283
#1  0x00007ffff7ef9f62 in lys_eval_iffeatures (ctx=0x55555556c2f0, iffeatures=0x55555559efa0,
    enabled=0x7fffffff8887 "\001") at /home/user1/libyang/src/schema_features.c:467
#2  0x00007ffff7ee1199 in lys_compile_type_enums (ctx=0x7fffffffa1e0, enums_p=0x5555555a3e88, basetype=LY_TYPE_ENUM,
    base_enums=0x0, bitenums=0x5555555713b8) at /home/user1/libyang/src/schema_compile_node.c:1307
#3  0x00007ffff7ee342c in lys_compile_type_ (ctx=0x7fffffffa1e0, context_pnode=0x5555555a3da0, context_flags=37,
    context_name=0x55555559e810 "load-balance", type_p=0x5555555a3df0, basetype=LY_TYPE_ENUM, tpdfname=0x0, base=0x0,
    type=0x5555555a3d80) at /home/user1/libyang/src/schema_compile_node.c:1535
#4  0x00007ffff7ee5383 in lys_compile_type (ctx=0x7fffffffa1e0, context_pnode=0x5555555a3da0, context_flags=37,
    context_name=0x55555559e810 "load-balance", type_p=0x5555555a3df0, type=0x5555555a3d80, units=0x5555555a3d88,
    dflt=0x7fffffff8b68) at /home/user1/libyang/src/schema_compile_node.c:1988
#5  0x00007ffff7ee8168 in lys_compile_node_type (ctx=0x7fffffffa1e0, context_node=0x5555555a3da0,
    type_p=0x5555555a3df0, leaf=0x5555555a3d20) at /home/user1/libyang/src/schema_compile_node.c:2670
#6  0x00007ffff7ee873e in lys_compile_node_leaf (ctx=0x7fffffffa1e0, pnode=0x5555555a3da0, node=0x5555555a3d20)
    at /home/user1/libyang/src/schema_compile_node.c:2726
#7  0x00007ffff7ee6ab4 in lys_compile_node_ (ctx=0x7fffffffa1e0, pnode=0x5555555a3da0, parent=0x555555571af0,
    uses_status=0, node_compile_spec=0x7ffff7ee8351 <lys_compile_node_leaf>, node=0x5555555a3d20, child_set=0x0)
    at /home/user1/libyang/src/schema_compile_node.c:2458
#8  0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffa1e0, pnode=0x5555555a00c0, parent=0x555555571af0,
    uses_status=0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:3900
#9  0x00007ffff7ee7cdd in lys_compile_node_container (ctx=0x7fffffffa1e0, pnode=0x55555559f750, node=0x555555571af0)
    at /home/user1/libyang/src/schema_compile_node.c:2632
#10 0x00007ffff7ee6ab4 in lys_compile_node_ (ctx=0x7fffffffa1e0, pnode=0x55555559f750, parent=0x555555571a60,
    uses_status=0, node_compile_spec=0x7ffff7ee7c51 <lys_compile_node_container>, node=0x555555571af0,
    child_set=0x7fffffff8ea0) at /home/user1/libyang/src/schema_compile_node.c:2458
#11 0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffa1e0, pnode=0x55555559f750, parent=0x555555571a60,
    uses_status=0, child_set=0x7fffffff8ea0) at /home/user1/libyang/src/schema_compile_node.c:3900
#12 0x00007ffff7ef685d in lys_compile_augment (ctx=0x7fffffffa1e0, aug_p=0x55555559f550, target=0x555555571a60)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /home/user1/libyang/src/schema_compile_amend.c:1747
#13 0x00007ffff7ef711a in lys_compile_node_augments (ctx=0x7fffffffa1e0, node=0x555555571a60) at /home/user1/libyang/src/schema_compile_amend.c:1918
#14 0x00007ffff7ee6a8e in lys_compile_node_ (ctx=0x7fffffffa1e0, pnode=0x55555558e160, parent=0x5555555719e0, uses_status=0, node_compile_spec=0x7ffff7ee9b45 <lys_compile_node_list>, node=0x555555571a60, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:2455
#15 0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffa1e0, pnode=0x55555558e160, parent=0x5555555719e0, uses_status=0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:3900
#16 0x00007ffff7ee7cdd in lys_compile_node_container (ctx=0x7fffffffa1e0, pnode=0x55555558df20, node=0x5555555719e0) at /home/user1/libyang/src/schema_compile_node.c:2632
#17 0x00007ffff7ee6ab4 in lys_compile_node_ (ctx=0x7fffffffa1e0, pnode=0x55555558df20, parent=0x0, uses_status=0, node_compile_spec=0x7ffff7ee7c51 <lys_compile_node_container>, node=0x5555555719e0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:2458
#18 0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffa1e0, pnode=0x55555558df20, parent=0x0, uses_status=0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:3900
#19 0x00007ffff7edb044 in lys_compile (mod=0x55555558d660, options=0, recompile=0 '\000', unres=0x7fffffffd7e0) at /home/user1/libyang/src/schema_compile.c:1674
#20 0x00007ffff7efd3f7 in lys_set_implemented_r (mod=0x55555558d660, features=0x0, unres=0x7fffffffd7e0) at /home/user1/libyang/src/tree_schema.c:834
#21 0x00007ffff7ef87cc in lys_precompile_augments_deviations (ctx=0x7fffffffb3d0) at /home/user1/libyang/src/schema_compile_amend.c:2275
#22 0x00007ffff7edaed3 in lys_compile (mod=0x55555559f240, options=0, recompile=0 '\000', unres=0x7fffffffd7e0) at /home/user1/libyang/src/schema_compile.c:1646
#23 0x00007ffff7efd3f7 in lys_set_implemented_r (mod=0x55555559f240, features=0x0, unres=0x7fffffffd7e0) at /home/user1/libyang/src/tree_schema.c:834
#24 0x00007ffff7ef87cc in lys_precompile_augments_deviations (ctx=0x7fffffffc5c0) at /home/user1/libyang/src/schema_compile_amend.c:2275
#25 0x00007ffff7edaed3 in lys_compile (mod=0x55555558aff0, options=0, recompile=0 '\000', unres=0x7fffffffd7e0) at /home/user1/libyang/src/schema_compile.c:1646
#26 0x00007ffff7efd3f7 in lys_set_implemented_r (mod=0x55555558aff0, features=0x55555556b620 <all_features>, unres=0x7fffffffd7e0) at /home/user1/libyang/src/tree_schema.c:834
#27 0x00007ffff7f001da in lys_create_module (ctx=0x55555556c2f0, in=0x55555558afa0, format=LYS_IN_YANG, need_implemented=1 '\001', custom_check=0x0, check_data=0x0, features=0x55555556b620 <all_features>, unres=0x7fffffffd7e0, module=0x7fffffffd8c0) at /home/user1/libyang/src/tree_schema.c:1407
#28 0x00007ffff7f00570 in lys_parse (ctx=0x55555556c2f0, in=0x55555558afa0, format=LYS_IN_YANG, features=0x55555556b620 <all_features>, module=0x7fffffffd8c0) at /home/user1/libyang/src/tree_schema.c:1479
#29 0x0000555555559387 in fill_context_inputs (argc=4, argv=0x7fffffffdea8, c=0x7fffffffdcc0) at /home/user1/libyang/tools/lint/main_ni.c:312
#30 0x000055555555a288 in fill_context (argc=4, argv=0x7fffffffdea8, c=0x7fffffffdcc0) at /home/user1/libyang/tools/lint/main_ni.c:669
#31 0x000055555555a4fe in main_ni (argc=4, argv=0x7fffffffdea8) at /home/user1/libyang/tools/lint/main_ni.c:712
#32 0x0000555555558e13 in main (argc=4, argv=0x7fffffffdea8) at /home/user1/libyang/tools/lint/main.c:45


Starting program: /home/user1/local/libyang2/bin/yanglint -p . vendor-ietf-snmp-deviations-ext.yang
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
libyang err : Memory allocation failed.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ef9734 in lys_compile_iffeature (ctx=0x55555556c2f0, qname=0x555555571d50, iff=0x7fffffff9850)
    at /home/user1/libyang/src/schema_features.c:283
283         for (i = j = 0; c[i]; i++) {
(gdb) bt
#0  0x00007ffff7ef9734 in lys_compile_iffeature (ctx=0x55555556c2f0, qname=0x555555571d50, iff=0x7fffffff9850)
    at /home/user1/libyang/src/schema_features.c:283
#1  0x00007ffff7ef9f62 in lys_eval_iffeatures (ctx=0x55555556c2f0, iffeatures=0x555555571d50,
    enabled=0x7fffffff98b7 "\001") at /home/user1/libyang/src/schema_features.c:467
#2  0x00007ffff7ee1199 in lys_compile_type_enums (ctx=0x7fffffffb3d0, enums_p=0x555555571ce8, basetype=LY_TYPE_ENUM,
    base_enums=0x0, bitenums=0x5555555c54f8) at /home/user1/libyang/src/schema_compile_node.c:1307
#3  0x00007ffff7ee342c in lys_compile_type_ (ctx=0x7fffffffb3d0, context_pnode=0x555555571c00, context_flags=5,
    context_name=0x5555555bb5e0 "context-match", type_p=0x555555571c50, basetype=LY_TYPE_ENUM, tpdfname=0x0, base=0x0,
    type=0x555555571be0) at /home/user1/libyang/src/schema_compile_node.c:1535
#4  0x00007ffff7ee5383 in lys_compile_type (ctx=0x7fffffffb3d0, context_pnode=0x555555571c00, context_flags=5,
    context_name=0x5555555bb5e0 "context-match", type_p=0x555555571c50, type=0x555555571be0, units=0x555555571be8,
    dflt=0x7fffffff9b98) at /home/user1/libyang/src/schema_compile_node.c:1988
#5  0x00007ffff7ee8168 in lys_compile_node_type (ctx=0x7fffffffb3d0, context_node=0x555555571c00,
    type_p=0x555555571c50, leaf=0x555555571b80) at /home/user1/libyang/src/schema_compile_node.c:2670
#6  0x00007ffff7ee873e in lys_compile_node_leaf (ctx=0x7fffffffb3d0, pnode=0x555555571c00, node=0x555555571b80)
    at /home/user1/libyang/src/schema_compile_node.c:2726
#7  0x00007ffff7ee6ab4 in lys_compile_node_ (ctx=0x7fffffffb3d0, pnode=0x555555571c00, parent=0x555555571970,
    uses_status=0, node_compile_spec=0x7ffff7ee8351 <lys_compile_node_leaf>, node=0x555555571b80, child_set=0x0)
    at /home/user1/libyang/src/schema_compile_node.c:2458
#8  0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffb3d0, pnode=0x5555555b8780, parent=0x555555571970,
    uses_status=0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:3900
#9  0x00007ffff7ee9c24 in lys_compile_node_list (ctx=0x7fffffffb3d0, pnode=0x5555555b84b0, node=0x555555571970)
    at /home/user1/libyang/src/schema_compile_node.c:3070
#10 0x00007ffff7ee6ab4 in lys_compile_node_ (ctx=0x7fffffffb3d0, pnode=0x5555555b84b0, parent=0x5555555716c0,
    uses_status=0, node_compile_spec=0x7ffff7ee9b45 <lys_compile_node_list>, node=0x555555571970, child_set=0x0)
    at /home/user1/libyang/src/schema_compile_node.c:2458
#11 0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffb3d0, pnode=0x5555555b84b0, parent=0x5555555716c0,
    uses_status=0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:3900
#12 0x00007ffff7ee9c24 in lys_compile_node_list (ctx=0x7fffffffb3d0, pnode=0x5555555b7b30, node=0x5555555716c0)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /home/user1/libyang/src/schema_compile_node.c:3070
#13 0x00007ffff7ee6ab4 in lys_compile_node_ (ctx=0x7fffffffb3d0, pnode=0x5555555b7b30, parent=0x555555571640, uses_status=0, node_compile_spec=0x7ffff7ee9b45 <lys_compile_node_list>, node=0x5555555716c0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:2458
#14 0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffb3d0, pnode=0x5555555b7b30, parent=0x555555571640, uses_status=0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:3900
#15 0x00007ffff7ee7cdd in lys_compile_node_container (ctx=0x7fffffffb3d0, pnode=0x5555555b7aa0, node=0x555555571640) at /home/user1/libyang/src/schema_compile_node.c:2632
#16 0x00007ffff7ee6ab4 in lys_compile_node_ (ctx=0x7fffffffb3d0, pnode=0x5555555b7aa0, parent=0x5555555b9e90, uses_status=0, node_compile_spec=0x7ffff7ee7c51 <lys_compile_node_container>, node=0x555555571640, child_set=0x7fffffffa1f0) at /home/user1/libyang/src/schema_compile_node.c:2458
#17 0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffb3d0, pnode=0x5555555b7aa0, parent=0x5555555b9e90, uses_status=0, child_set=0x7fffffffa1f0) at /home/user1/libyang/src/schema_compile_node.c:3900
#18 0x00007ffff7ef685d in lys_compile_augment (ctx=0x7fffffffb3d0, aug_p=0x5555555b7a30, target=0x5555555b9e90) at /home/user1/libyang/src/schema_compile_amend.c:1747
#19 0x00007ffff7ef711a in lys_compile_node_augments (ctx=0x7fffffffb3d0, node=0x5555555b9e90) at /home/user1/libyang/src/schema_compile_amend.c:1918
#20 0x00007ffff7ee6a8e in lys_compile_node_ (ctx=0x7fffffffb3d0, pnode=0x55555559a870, parent=0x0, uses_status=0, node_compile_spec=0x7ffff7ee7c51 <lys_compile_node_container>, node=0x5555555b9e90, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:2455
#21 0x00007ffff7eec733 in lys_compile_node (ctx=0x7fffffffb3d0, pnode=0x55555559a870, parent=0x0, uses_status=0, child_set=0x0) at /home/user1/libyang/src/schema_compile_node.c:3900
#22 0x00007ffff7edb568 in lys_compile (mod=0x5555555905c0, options=0, recompile=0 '\000', unres=0x7fffffffd7e0) at /home/user1/libyang/src/schema_compile.c:1696
#23 0x00007ffff7efd3f7 in lys_set_implemented_r (mod=0x5555555905c0, features=0x0, unres=0x7fffffffd7e0) at /home/user1/libyang/src/tree_schema.c:834
#24 0x00007ffff7ef87cc in lys_precompile_augments_deviations (ctx=0x7fffffffc5c0) at /home/user1/libyang/src/schema_compile_amend.c:2275
#25 0x00007ffff7edaed3 in lys_compile (mod=0x55555558aff0, options=0, recompile=0 '\000', unres=0x7fffffffd7e0) at /home/user1/libyang/src/schema_compile.c:1646
#26 0x00007ffff7efd3f7 in lys_set_implemented_r (mod=0x55555558aff0, features=0x55555556b620 <all_features>, unres=0x7fffffffd7e0) at /home/user1/libyang/src/tree_schema.c:834
#27 0x00007ffff7f001da in lys_create_module (ctx=0x55555556c2f0, in=0x55555558afa0, format=LYS_IN_YANG, need_implemented=1 '\001', custom_check=0x0, check_data=0x0, features=0x55555556b620 <all_features>, unres=0x7fffffffd7e0, module=0x7fffffffd8c0) at /home/user1/libyang/src/tree_schema.c:1407
#28 0x00007ffff7f00570 in lys_parse (ctx=0x55555556c2f0, in=0x55555558afa0, format=LYS_IN_YANG, features=0x55555556b620 <all_features>, module=0x7fffffffd8c0) at /home/user1/libyang/src/tree_schema.c:1479
#29 0x0000555555559387 in fill_context_inputs (argc=4, argv=0x7fffffffdea8, c=0x7fffffffdcc0) at /home/user1/libyang/tools/lint/main_ni.c:312
#30 0x000055555555a288 in fill_context (argc=4, argv=0x7fffffffdea8, c=0x7fffffffdcc0) at /home/user1/libyang/tools/lint/main_ni.c:669
#31 0x000055555555a4fe in main_ni (argc=4, argv=0x7fffffffdea8) at /home/user1/libyang/tools/lint/main_ni.c:712
#32 0x0000555555558e13 in main (argc=4, argv=0x7fffffffdea8) at /home/user1/libyang/tools/lint/main.c:45
```

**Comment by michalvasko** [comment]
I should be fine just with a reproducible example so please attach the YANG modules.

**Comment by gvub** [comment]
[vendor-ietf-snmp-deviations-ext.zip](https://github.com/CESNET/libyang/files/6671454/vendor-ietf-snmp-deviations-ext.zip)
On my side, I can reproduce a similar issue by dropping the file attached into the IETF RFC folder of https://github.com/YangModels/yang

Note that on my installation, test 2 (format) has always failed since the switch to libyang2.

**Comment by michalvasko** [comment]
Okay, should work now. As for the format problem, I guess you are using `uncrustify` v0.72. We have written the config file for v0.71 and it seems there are some implicit differences.

**Comment by gvub** [comment]
That particular case is fixed. Thanks a lot. 
However, I still encounter segfaults on other modules.
You may reproduce using files from this public repository: https://github.com/Huawei/yang

Looping through the atn980b subfolder as follows triggers some segfaults/aborts:
```
for f in `grep -L submodule *.yang`; do echo "Validating... " $f ; yanglint -p . $f 2> /dev/null; done
```

**Comment by michalvasko** [comment]
Okay, all of those should work now.

**Comment by gvub** [comment]
Hello again. It works better now, thanks for the effort! but I still face issues in other cases: 
Based on today's devel branch (yanglint 2.0.24), the yang file attached generates a segfault (you can place it in the RFC folder of https://github.com/YangModels/yang)

[test-ietf-ip-deviations.zip](https://github.com/CESNET/libyang/files/6710665/test-ietf-ip-deviations.zip)

**Comment by michalvasko** [comment]
Should no longer crash.

**Comment by gvub** [comment]
It works now. Thanks again.
