### ISSUE TITLE
yanglint tree generation fails with error

### ISSUE THREAD

**Issue by iGovindY** [CESNET/libyang#1664]
Hi, 

yanglint with version 2.0.54, gives below error 

```
[root@pwredg85021 myyangs]# yanglint -f tree *.yang >/tmp/govi
libyang err : Augment target node "/me3gpp:ManagedElement/gnbcucp3gpp:GNBCUCPFunction" from module "_3gpp-nr-nrm-ep" was not found. (/_3gpp-nr-nrm-ep:{augment='/me3gpp:ManagedElement/gnbcucp3gpp:GNBCUCPFunction'})
libyang err : Augment target node "/me3gpp:ManagedElement/gnbcuup3gpp:GNBCUUPFunction" from module "_3gpp-nr-nrm-ep" was not found. (/_3gpp-nr-nrm-ep:{augment='/me3gpp:ManagedElement/gnbcuup3gpp:GNBCUUPFunction'})
YANGLINT[E]: Processing schema module from mymodule.yang failed.
[root@pwredg85021 myyangs]# yanglint --version
yanglint 2.0.54
[root@pwredg85021 myyangs]# 
```
below is the yangs needed to reproduce this
[yang_files.tar.gz](https://github.com/CESNET/libyang/files/6862513/yang_files.tar.gz)

### Steps
1. untar above zip.
2. cd myyangs
3. yanglint -f tree *.yang >/tmp/govi

**Comment by iGovindY** [comment]
same issue we get while installing modules to sysrepo.

**Comment by michalvasko** [comment]
An interesting use-case, should now work with the latest `devel`.

**Comment by meghna-doshi** [comment]
Hi Michal,
I have pulled these changes from devel branch but still see something related issue.
Yang tar file attached.
yanglint --version
yanglint 2.0.66

[issueyang.zip](https://github.com/CESNET/libyang/files/6929791/issueyang.zip)


yanglint -f tree *.yang

```
libyang err : Not found node "user-plane-configuration" in path. (Schema location /o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-uplane-conf:uplane-conf-model/user-plane-configuration/relations/array1/antenna-type/tx/tx-array-name.)
libyang err : Target of leafref "tx-array-name" cannot be referenced because it is disabled. (Schema location /o-ran-aggregation-base:aggregated-o-ru/aggregation/o-ran-agg-uplane-conf:uplane-conf-model/user-plane-configuration/relations/array1/antenna-type/tx/tx-array-name.)
YANGLINT[E]: Processing schema module from o-ran-ru.yang failed.

```

**Comment by michalvasko** [comment]
In this case the error is intentional and arguably valid. You have removed the leafref target by a deviation meaning you can never create a valid instance of the leafref. It may not be mandated by the specification but there is a similar requirement (of having the same set of `if-feature` statements) with possibly the same motivation. So I am not sure what to do but am inclined to say the particular set of modules is not valid together.

**Comment by meghna-doshi** [comment]
Hi Michal,
Somehow i think this understanding is not correct:

`You have removed the leafref target by a deviation meaning you can never create a valid instance of the leafref`

Lets take a simple xpath example:
1. lets say there is a base.yang which has some container whose xpath is say /base:baseContainer/
2. there is another yang, derived.yang which augments base like :   /derived:derivedContainer/base:baseContainer
3. so now system wants to support xpath of (2) and not (1), so we have to do 
/base:baseContainer/ {devaite not-supported)

I dont see any reason why a system is forced to support both (1) and (2) xpaths. There are many systems which can augment from some base yangs and then have their own implementations.

I hope i made myself clear. 

Also lets say if with current implementation this cannot be fixed, can you suggest some yang syntax how to support xpath of (2) and fail for xpath (1).

Regards,
Meghna

**Comment by michalvasko** [comment]
I am sorry but I did not understand what your exact use-case is. I have attached simple modules to illustrate what I consider to be an invalid situation similar to those in your modules. Please try to provide an example as well to show what you are trying to achieve.

[example.tar.gz](https://github.com/CESNET/libyang/files/6937360/example.tar.gz)

**Comment by meghna-doshi** [comment]
Yes right Michal, i think i missed noticing that there were some leafrefs which were pointing to deviated path.
Will try again after changing such leafrefs and check.
Thanks for the response.
