### ISSUE TITLE
ly_ctx_remove_module function may be have bug

### ISSUE THREAD

**Issue by gcbgitbub** [CESNET/libyang#575]
```C
    for (i = o = LY_INTERNAL_MODULE_COUNT; i < ctx->models.used; i++) {
        if (ctx->models.list[o]) {
            /* used cell */
            o++;
        } else {
            /* the current output cell is empty, move here an input cell */
            ctx->models.list[o] = ctx->models.list[i];
            ctx->models.list[i] = NULL;
        }
    }
```

this logic will remove empty element, but when i not equal o, will skip some valid element,
i think should like this
```C
    for (i = o = LY_INTERNAL_MODULE_COUNT; i < ctx->models.used; i++) {
        if (ctx->models.list[i]) {
            /* used cell */
            ctx->models.list[o] = ctx->models.list[i];
            if (o != i)
            {
                ctx->models.list[i] = NULL;
            }
            o++;
        }
    }
```

**Comment by michalvasko** [comment]
Hi,
where is this code from? I failed to find it in the current *libyang*.

Regards,
Michal

**Comment by gcbgitbub** [comment]
libyang-master\src\context.c

**Comment by michalvasko** [comment]
Hi,
the loop is just moving current modules so that there are no empty spaces in the array. Please, do not post issues like this. If you have an actual problem using *libyang*, then you can create an issue.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
I have added some checks into a test that cover the use-case when a hole appears in the context, it works as expected. Unless you provide a specific non-working use-case, I will not reply anymore as I have better things to do than to debug working code.

Regards,
Michal

**Comment by lyzliyuzhi91** [comment]
Hi,
I write an test code according to code mentioned by gcbgitbub, and I think what gcbgitbub  said is right, some elements will be ignored because the value of "used" was wrong.

void test_biptr()
{
	size_t i, o, used = 85;
	int list[85] = {0};
	for (size_t i = 0; i < used; i++) {
		list[i] = i + 1;
	}
    // the "84" module was removed by caller, 
    // the "46" module was autoremove because it is an import-only module and nobody import it
	list[84] = list[46] = 0;
	
	for (i = o = 3; i < 85; i++) {
		if (list[o]) {
			o++;
		} else {
			list[o] = list[i];
			list[i] = 0;
		}
	}
	
	while (!list[o]) {
		o--;
	}
	
	size_t new_used = o + 1;
	printf("new_used:%d\n", new_used);   // 77, not 85 - 2, so wrong
}

The variable "new_used" is corresponding to "used" member of ly_ctx。
Thanks

**Comment by michalvasko** [comment]
Okay, thanks for the example, should be fixed now.

**Comment by lyzliyuzhi91** [comment]
Hi, I update my test code according to your commit, and i think there still exist some problem,


void test_biptr() {
    size_t i, o, used = 85;
	int list[85] = { 0 };
	for (size_t i = 0; i < used; i++) {
		list[i] = i + 1;
	}
	// the "84" module was removed by caller, 
	// the "46" module was auto removed because it is an import-only module and nobody import it
	list[84] = list[46] = 0;

	for (i = o = 3; i < used; i++, o++) {
		if (!list[o]) {
			while (!list[i]) {
				++i;
				if (i == used) {
					break;
				}
			}
			list[o] = list[i];
			list[i] = 0;
		}
	}

	while (!list[o]) {
		o--;
	}

	size_t new_used = o + 1;
	printf("new_used:%d\n", new_used);   // 84, not 85 - 2, wrong still??
}

i think the new used variable is still wrong.
thanks.

**Comment by michalvasko** [comment]
That is strange. I have attached the example I used, which prints 83, so there is something else wrong.

[main.c.txt](https://github.com/CESNET/libyang/files/6180055/main.c.txt)

**Comment by lyzliyuzhi91** [comment]
So weird, I ran the code in two different machine, the "new_used" variable in both machine are "84", the variable "o" are "83".

**Comment by michalvasko** [comment]
Hm, not really. Now it is hopefully finally fixed.
